spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: m.alsadi@eskadenia.com
    password: Eska1234
    port: 3306
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false